### ISSUE TITLE
pango >= 1.44 requires harfbuzz; have to tell cmake where to find it

### ISSUE THREAD

**Issue by quequotion** [pcsxr/PCSX-Reloaded#5]
Fails to build from source in Archlinux with:
```
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/gtk-3.0/gdk/gdktypes.h:35,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /startdir/src/pcsxr/pcsxr/plugins/peopsxgl/gpucfg/main.c:1:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
```
I think the problem could be solved by telling cmake where to find harfbuzz. [Gnome regards this as a problem with dependent software](https://gitlab.gnome.org/GNOME/pango/issues/387)

For example, EiskaltDC++ [fixed this problem](https://github.com/eiskaltdcpp/eiskaltdcpp/commit/8b22479aef21fb2b764051f0499ae5fba397d31f).

**Comment by uyjulian** [comment]
This is a mirror repository

**Comment by quequotion** [comment]
Aw, snap. Didn't read the header.

[pcsxr-git](https://aur.archlinux.org/packages/pcxr-git) in the AUR builds this repository.

Seems like the [official svn](https://pcsxr.svn.codeplex.com/svn/pcsxr) no longer exists, and their site is 'archived'. 

I found a few forks on github, but nothing that looks like a replacement. Is there a better place to report problems?

**Comment by uyjulian** [comment]
Probably not, since the main developers are no longer working on it. edgbla is busy with other things, so he can't work on it.

I would probably use this one: https://github.com/iCatButler/pcsxr  

In fact, there is already a PR related to this issue: https://github.com/iCatButler/pcsxr/pull/16

**Comment by quequotion** [comment]
Seems like they'll get around to fixing this for pcsxr-pgxp eventually.

**Comment by tallero** [comment]
This problem was fixed in this project's [AUR package](https://aur.archlinux.org/packages/pcsxr-git/).
